#spring:
#  application:
#    name: Survey
#  datasource:
#    password: 12345
#    url: jdbc:postgresql://localhost:5432/healthbizz
#    username: postgres
##  jpa:
##    hibernate:
###      ddl-auto: create
##    show-sql: true
#
#  liquibase:
#    change-log: classpath:db/changelog/schema.sql
#    enabled: true